### ISSUE TITLE
MultipleFeaturizer does not work with featurizers returning matrices

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#298]
The following code illustrates the problem:

```python
from matminer.datasets.dataframe_loader import load_elastic_tensor
df = load_elastic_tensor()[:5]
featurizers = [sf.GlobalSymmetryFeatures(), sf.CoulombMatrix()]

# Fails
mf = MultipleFeaturizer(featurizers)
mf.fit_featurize_dataframe(df, "structure", ignore_errors=True)

# Works
# for f in featurizers:
#     df = f.featurize_dataframe(df, "structure", ignore_errors=True)
```

The stacktrace is:
```
MultipleFeaturizer: 100%|██████████| 5/5 [00:00<00:00, 320.58it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/ardunn/alex/lbl/projects/common_env/dev_codes/matminer/matminer/featurizers/base.py", line 442, in featurize_wrapper
    for f in self.featurizers])
  File "/Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages/numpy/core/shape_base.py", line 286, in hstack
    return _nx.concatenate(arrs, 0)
ValueError: all the input arrays must have same number of dimensions
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ardunn/alex/lbl/projects/matbench/matbench/matbench/featurize.py", line 564, in <module>
    mf.fit_featurize_dataframe(df, "structure", ignore_errors=True)
  File "/Users/ardunn/alex/lbl/projects/common_env/dev_codes/matminer/matminer/featurizers/base.py", line 160, in fit_featurize_dataframe
    **kwargs)
  File "/Users/ardunn/alex/lbl/projects/common_env/dev_codes/matminer/matminer/featurizers/base.py", line 217, in featurize_dataframe
    pbar=pbar)
  File "/Users/ardunn/alex/lbl/projects/common_env/dev_codes/matminer/matminer/featurizers/base.py", line 320, in featurize_many
    return p.map(func, entries)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: all the input arrays must have same number of dimensions
```

The problem persists with any featurizer returning a matrix (e.g., OrbitalFieldMatrix)

**Comment by utf** [comment]
This is now fixed by #319
