### ISSUE TITLE
All builds failing because of MDF forge

### ISSUE THREAD

**Issue by ardunn** [hackingmaterials/matminer#325]
All new builds (including recent otherwise fine pull requests #322, #321) of matminer are broken because:

```
======================================================================
ERROR: test suite for <class 'test_retrieve_MDF.MDFDataRetrievalTest'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/matminer/.tox/py36/lib/python3.6/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/circleci/matminer/.tox/py36/lib/python3.6/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/circleci/matminer/.tox/py36/lib/python3.6/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/circleci/matminer/.tox/py36/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/circleci/matminer/matminer/data_retrieval/tests/test_retrieve_MDF.py", line 21, in setUpClass
    cls.oqmd_version = cls.mdf_dr.forge.get_dataset_version('oqmd')
  File "/home/circleci/matminer/.tox/py36/lib/python3.6/site-packages/mdf_forge/forge.py", line 710, in get_dataset_version
    raise ValueError("No such dataset found: " + source_name)
ValueError: No such dataset found: oqmd
```

This should be a priority to fix...

**Comment by WardLT** [comment]
We are currently rebuilding the MDF search index. I'll disable the tests
for now, as it will be a few more days until that process is complete.

Sorry, should have remembered to disable them beforehand

**Comment by WardLT** [comment]
Alright, the builds now pass. I'm currently working on the MDF-side of this problem, and will leave this issue open until I fix that.

**Comment by WardLT** [comment]
The upgrade of the MDF search index finished on Friday. I'll probably get
to fixing the texts on Monday
